version: '3.8'

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: tommy-it-tools_app_1
      APP_PORT: 80

  app:
    image: corentinth/it-tools:latest
    restart: unless-stopped
